services:
  {{PROJECT}}_app:
    build:
      context: ./docker
      args:
        INSTALL_GD: "${INSTALL_GD:-false}"
        INSTALL_IMAGICK: "${INSTALL_IMAGICK:-false}"
        INSTALL_EXIF: "${INSTALL_EXIF:-false}"
    container_name: {{PROJECT}}.prj.loc-php
    volumes:
      - ./{{PROJECT}}:/var/www/html
      - ${SSH_PRIVATE_KEY_PATH}:/tmp/ssh/id_rsa:ro
      - ${SSH_PUBLIC_KEY_PATH}:/tmp/ssh/id_rsa.pub:ro
      - ${SSH_KNOWN_HOSTS_PATH}:/tmp/ssh/known_hosts:ro
    environment:
      PHP_IDE_CONFIG: serverName={{PROJECT}}.prj.loc
      GIT_AUTHOR_NAME:     ${GIT_AUTHOR_NAME}
      GIT_AUTHOR_EMAIL:    ${GIT_AUTHOR_EMAIL}
      GIT_COMMITTER_NAME:  ${GIT_COMMITTER_NAME}
      GIT_COMMITTER_EMAIL: ${GIT_COMMITTER_EMAIL}

    networks:
      - proxy
      - internal

  nginx:
    image: nginx:stable
    container_name: {{PROJECT}}.prj.loc-nginx
    volumes:
      - ./{{PROJECT}}:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - {{PROJECT}}_app
    networks:
      - proxy
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{{PROJECT}}.rule=Host(`{{PROJECT}}.prj.loc`)"
      - "traefik.http.routers.{{PROJECT}}.entrypoints=websecure"
      - "traefik.http.routers.{{PROJECT}}.tls=true"
      - "traefik.http.routers.{{PROJECT}}.middlewares=https-redirect"
      - "traefik.http.services.{{PROJECT}}.loadbalancer.server.port=80"

      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"

  db:
    image: postgres:15
    container_name: {{PROJECT}}.prj.loc-db
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel
      POSTGRES_DB: db_{{PROJECT}}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal
    ports:
      - "{{DB_PORT}}:5432"

  redis:
    image: redis:alpine
    container_name: {{PROJECT}}.prj.loc-redis
    networks:
      - internal

  worker:
    build:
      context: ./docker
      args:
        INSTALL_GD: "${INSTALL_GD:-false}"
        INSTALL_IMAGICK: "${INSTALL_IMAGICK:-false}"
        INSTALL_EXIF: "${INSTALL_EXIF:-false}"
    container_name: {{PROJECT}}.prj.loc-worker
    command: php artisan queue:work redis --queue=default --sleep=3 --tries=3 --max-time=3600
    volumes:
      - ./{{PROJECT}}:/var/www/html
    depends_on:
      - redis
      - db
    environment:
      PHP_IDE_CONFIG: serverName={{PROJECT}}.prj.loc
      GIT_AUTHOR_NAME:     ${GIT_AUTHOR_NAME}
      GIT_AUTHOR_EMAIL:    ${GIT_AUTHOR_EMAIL}
      GIT_COMMITTER_NAME:  ${GIT_COMMITTER_NAME}
      GIT_COMMITTER_EMAIL: ${GIT_COMMITTER_EMAIL}
    restart: unless-stopped
    networks:
      - internal

  node:
    image: node:20
    container_name: {{PROJECT}}.prj.loc-node
    working_dir: /var/www/html
    volumes:
      - ./{{PROJECT}}:/var/www/html
    command: tail -f /dev/null
    networks:
      - proxy
      - internal

networks:
  proxy:
    external: true
  internal:

volumes:
  pgdata:
