up:
	docker compose up -d

down:
	docker compose down

restart:
	docker compose down && docker compose up -d

logs:
	docker compose logs -f

composer-install:
	docker compose exec app composer install

dost:
	cd ~/code/docker-dev/projects/dostoverno.prj.loc
