FROM php:{{PHP_VERSION}}-fpm

RUN apt-get update && apt-get install -y \
    git unzip libpq-dev supervisor mc \
    libzip-dev libpng-dev libjpeg-dev libfreetype6-dev \
    libmagickwand-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install \
        pdo \
        pdo_pgsql \
        bcmath \
        zip \
        gd \
        pcntl \
        exif \
    && pecl install redis imagick xdebug \
    && docker-php-ext-enable redis imagick xdebug \
    && mkdir -p /var/log/supervisor \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY conf.d/xdebug.ini /usr/local/etc/php/conf.d/99-xdebug.ini
COPY php-fpm.d/zz-env.conf /usr/local/etc/php-fpm.d/zz-env.conf
COPY supervisor/supervisord.conf /etc/supervisor/supervisord.conf

WORKDIR /var/www/html

CMD ["supervisord", "-n", "-c", "/etc/supervisor/supervisord.conf"]
